### Переменные окружения
@baseUrl = http://localhost:3000
@fileDirectory = /home/vez/work/calm-wiki/raw/images

### Загрузка нескольких скриншотов (до 10 файлов за раз)
POST {{baseUrl}}/api/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="2026-09-25_github-174977-fintech-response-handler.png"
Content-Type: image/png

< {{fileDirectory}}/2026-09-25_github-174977-fintech-response-handler.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="2026-09-25_teams-noel-java17-identify-repos.png"
Content-Type: image/png

< {{fileDirectory}}/2026-09-25_teams-noel-java17-identify-repos.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="2026-09-25_jira-c175021a-3316-cases-filled.png"
Content-Type: image/png

< {{fileDirectory}}/2026-09-25_jira-c175021a-3316-cases-filled.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--